-- SQLite baseline for locally persisted investment plans.
--
-- IDs, exact decimal amounts, and timestamps are stored as TEXT. IDs are
-- generated by the Rust domain layer. Amounts use a fixed 12-digit integer
-- part and 8-digit fractional part so SQLite can compare them lexically
-- without floating-point precision loss.

CREATE TABLE investment_plans (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    symbol TEXT NOT NULL,
    base_contribution TEXT NOT NULL,
    currency TEXT NOT NULL,
    schedule_kind TEXT NOT NULL DEFAULT 'monthly',
    schedule_day INTEGER NOT NULL,
    max_single_execution TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),

    CONSTRAINT investment_plans_name_normalized_check
        CHECK (name = trim(name) AND length(name) BETWEEN 1 AND 100),
    CONSTRAINT investment_plans_symbol_normalized_check
        CHECK (
            symbol = trim(symbol)
            AND symbol = upper(symbol)
            AND length(symbol) BETWEEN 1 AND 32
            AND length(CAST(symbol AS BLOB)) = length(symbol)
        ),
    CONSTRAINT investment_plans_currency_check
        CHECK (currency GLOB '[A-Z][A-Z][A-Z]'),
    CONSTRAINT investment_plans_schedule_kind_check
        CHECK (schedule_kind = 'monthly'),
    CONSTRAINT investment_plans_schedule_day_check
        CHECK (schedule_day BETWEEN 1 AND 28),
    CONSTRAINT investment_plans_base_contribution_not_blank_check
        CHECK (
            base_contribution GLOB '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
            AND base_contribution > '000000000000.00000000'
        ),
    CONSTRAINT investment_plans_max_single_execution_not_blank_check
        CHECK (
            max_single_execution GLOB '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
            AND max_single_execution > '000000000000.00000000'
        ),
    CONSTRAINT investment_plans_max_single_execution_gte_base_check
        CHECK (max_single_execution >= base_contribution),
    CONSTRAINT investment_plans_is_active_check
        CHECK (is_active IN (0, 1)),
    CONSTRAINT investment_plans_updated_after_created_check
        CHECK (
            strftime('%Y-%m-%dT%H:%M:%fZ', created_at) IS NOT NULL
            AND strftime('%Y-%m-%dT%H:%M:%fZ', created_at) = created_at
            AND strftime('%Y-%m-%dT%H:%M:%fZ', updated_at) IS NOT NULL
            AND strftime('%Y-%m-%dT%H:%M:%fZ', updated_at) = updated_at
            AND updated_at >= created_at
        )
);

CREATE INDEX investment_plans_created_at_id_idx
    ON investment_plans (created_at ASC, id ASC);

CREATE INDEX investment_plans_active_schedule_idx
    ON investment_plans (is_active, schedule_kind, schedule_day);
