-- SQLite baseline for locally persisted investment plans.
--
-- IDs and exact decimal amounts are stored as TEXT. IDs are generated by the
-- Rust domain layer, while amount normalization and comparison remain domain
-- invariants to avoid SQLite floating-point precision loss.

CREATE TABLE investment_plans (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    symbol TEXT NOT NULL,
    base_contribution TEXT NOT NULL,
    currency TEXT NOT NULL,
    schedule_kind TEXT NOT NULL DEFAULT 'monthly',
    schedule_day INTEGER NOT NULL,
    max_single_execution TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),

    CONSTRAINT investment_plans_name_normalized_check
        CHECK (name = trim(name) AND length(name) BETWEEN 1 AND 100),
    CONSTRAINT investment_plans_symbol_normalized_check
        CHECK (
            symbol = trim(symbol)
            AND symbol = upper(symbol)
            AND length(symbol) BETWEEN 1 AND 32
            AND length(CAST(symbol AS BLOB)) = length(symbol)
        ),
    CONSTRAINT investment_plans_currency_check
        CHECK (currency GLOB '[A-Z][A-Z][A-Z]'),
    CONSTRAINT investment_plans_schedule_kind_check
        CHECK (schedule_kind = 'monthly'),
    CONSTRAINT investment_plans_schedule_day_check
        CHECK (schedule_day BETWEEN 1 AND 28),
    CONSTRAINT investment_plans_base_contribution_not_blank_check
        CHECK (length(base_contribution) > 0),
    CONSTRAINT investment_plans_max_single_execution_not_blank_check
        CHECK (length(max_single_execution) > 0),
    CONSTRAINT investment_plans_is_active_check
        CHECK (is_active IN (0, 1)),
    CONSTRAINT investment_plans_updated_after_created_check
        CHECK (updated_at >= created_at)
);

CREATE INDEX investment_plans_created_at_id_idx
    ON investment_plans (created_at ASC, id ASC);

CREATE INDEX investment_plans_active_schedule_idx
    ON investment_plans (is_active, schedule_kind, schedule_day);
