#![forbid(unsafe_code)]
#![warn(missing_docs)]

//! Broker boundary for demo and future real trading adapters.
//!
//! This crate defines a provider-neutral broker port plus a safe mock
//! implementation. Real Futu/Moomoo OpenD integration should implement
//! [`BrokerClient`] in an adapter crate while preserving these invariants:
//! paper trading is the default demo path, live trading must be explicitly
//! enabled, and public errors must not expose account credentials.

use std::sync::Mutex;

use async_trait::async_trait;
use rust_decimal::Decimal;
use serde::Serialize;

const MAX_SYMBOL_LEN: usize = 32;
const MAX_IDEMPOTENCY_KEY_LEN: usize = 128;

/// Broker execution environment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum BrokerEnvironment {
    /// Paper trading or virtual-account execution.
    Paper,
    /// Real account execution; must be explicitly enabled by the adapter.
    Live,
}

/// Broker order side.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum BrokerOrderSide {
    /// Buy the instrument.
    Buy,
    /// Sell the instrument.
    Sell,
}

/// Broker order type supported by the MVP boundary.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum BrokerOrderType {
    /// Market order; no limit price is accepted.
    Market,
    /// Limit order; a positive limit price is required.
    Limit,
}

/// Validated broker order request.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct BrokerOrderRequest {
    /// Stable idempotency key generated by the execution layer.
    idempotency_key: String,
    /// Broker symbol, normalized to uppercase ASCII.
    symbol: String,
    /// Order side.
    side: BrokerOrderSide,
    /// Order type.
    order_type: BrokerOrderType,
    /// Positive order quantity.
    #[serde(with = "rust_decimal::serde::str")]
    quantity: Decimal,
    /// Positive limit price when `order_type` is limit.
    #[serde(
        default,
        with = "rust_decimal::serde::str_option",
        skip_serializing_if = "Option::is_none"
    )]
    limit_price: Option<Decimal>,
    /// Paper or live trading environment.
    environment: BrokerEnvironment,
}

impl BrokerOrderRequest {
    /// Build a validated market order request.
    pub fn market(
        idempotency_key: impl Into<String>,
        symbol: impl Into<String>,
        side: BrokerOrderSide,
        quantity: Decimal,
        environment: BrokerEnvironment,
    ) -> Result<Self, BrokerValidationError> {
        Self::new(
            idempotency_key,
            symbol,
            side,
            BrokerOrderType::Market,
            quantity,
            None,
            environment,
        )
    }

    /// Build a validated limit order request.
    pub fn limit(
        idempotency_key: impl Into<String>,
        symbol: impl Into<String>,
        side: BrokerOrderSide,
        quantity: Decimal,
        limit_price: Decimal,
        environment: BrokerEnvironment,
    ) -> Result<Self, BrokerValidationError> {
        Self::new(
            idempotency_key,
            symbol,
            side,
            BrokerOrderType::Limit,
            quantity,
            Some(limit_price),
            environment,
        )
    }

    fn new(
        idempotency_key: impl Into<String>,
        symbol: impl Into<String>,
        side: BrokerOrderSide,
        order_type: BrokerOrderType,
        quantity: Decimal,
        limit_price: Option<Decimal>,
        environment: BrokerEnvironment,
    ) -> Result<Self, BrokerValidationError> {
        let idempotency_key = normalize_idempotency_key(idempotency_key.into())?;
        let symbol = normalize_symbol(symbol.into())?;
        validate_positive("quantity", quantity)?;

        match (order_type, limit_price) {
            (BrokerOrderType::Market, None) => {}
            (BrokerOrderType::Market, Some(_)) => {
                return Err(BrokerValidationError::UnexpectedLimitPrice)
            }
            (BrokerOrderType::Limit, Some(price)) => validate_positive("limit_price", price)?,
            (BrokerOrderType::Limit, None) => return Err(BrokerValidationError::MissingLimitPrice),
        }

        Ok(Self {
            idempotency_key,
            symbol,
            side,
            order_type,
            quantity,
            limit_price,
            environment,
        })
    }

    /// Return the stable idempotency key.
    #[must_use]
    pub fn idempotency_key(&self) -> &str {
        &self.idempotency_key
    }

    /// Return the normalized symbol.
    #[must_use]
    pub fn symbol(&self) -> &str {
        &self.symbol
    }

    /// Return the order side.
    #[must_use]
    pub fn side(&self) -> BrokerOrderSide {
        self.side
    }

    /// Return the order type.
    #[must_use]
    pub fn order_type(&self) -> BrokerOrderType {
        self.order_type
    }

    /// Return the positive quantity.
    #[must_use]
    pub fn quantity(&self) -> Decimal {
        self.quantity
    }

    /// Return the optional limit price.
    #[must_use]
    pub fn limit_price(&self) -> Option<Decimal> {
        self.limit_price
    }

    /// Return the execution environment.
    #[must_use]
    pub fn environment(&self) -> BrokerEnvironment {
        self.environment
    }
}

/// Broker order response returned by adapters.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct BrokerOrderAck {
    /// Adapter-specific order ID.
    order_id: String,
    /// Accepted execution environment.
    environment: BrokerEnvironment,
    /// Initial broker-side status.
    status: BrokerOrderStatus,
}

impl BrokerOrderAck {
    /// Build a broker order acknowledgement.
    pub fn new(
        order_id: impl Into<String>,
        environment: BrokerEnvironment,
        status: BrokerOrderStatus,
    ) -> Result<Self, BrokerValidationError> {
        let order_id = normalize_idempotency_key(order_id.into())?;
        Ok(Self {
            order_id,
            environment,
            status,
        })
    }

    /// Return the adapter-specific order ID.
    #[must_use]
    pub fn order_id(&self) -> &str {
        &self.order_id
    }

    /// Return the accepted execution environment.
    #[must_use]
    pub fn environment(&self) -> BrokerEnvironment {
        self.environment
    }

    /// Return the initial broker-side status.
    #[must_use]
    pub fn status(&self) -> BrokerOrderStatus {
        self.status
    }
}

/// Initial broker order status.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum BrokerOrderStatus {
    /// Adapter accepted the order.
    Accepted,
    /// Adapter deduplicated a repeated idempotency key.
    Duplicate,
}

/// Broker port implemented by mock, paper, and live adapters.
#[async_trait]
pub trait BrokerClient: Send + Sync {
    /// Submit one validated broker order.
    async fn submit_order(
        &self,
        request: BrokerOrderRequest,
    ) -> Result<BrokerOrderAck, BrokerError>;
}

/// Safe broker implementation for demos and tests.
#[derive(Debug, Default)]
pub struct MockBroker {
    accepted: Mutex<Vec<BrokerOrderRequest>>,
    allow_live: bool,
}

impl MockBroker {
    /// Create a mock broker that accepts paper orders and rejects live orders.
    #[must_use]
    pub fn paper_only() -> Self {
        Self::default()
    }

    /// Create a mock broker that also accepts live-mode requests.
    #[must_use]
    pub fn allow_live() -> Self {
        Self {
            accepted: Mutex::new(Vec::new()),
            allow_live: true,
        }
    }

    /// Return a snapshot of accepted orders.
    #[must_use]
    pub fn accepted_orders(&self) -> Vec<BrokerOrderRequest> {
        self.accepted.lock().unwrap().clone()
    }
}

#[async_trait]
impl BrokerClient for MockBroker {
    async fn submit_order(
        &self,
        request: BrokerOrderRequest,
    ) -> Result<BrokerOrderAck, BrokerError> {
        if request.environment() == BrokerEnvironment::Live && !self.allow_live {
            return Err(BrokerError::LiveTradingDisabled);
        }

        let mut accepted = self.accepted.lock().unwrap();
        if accepted
            .iter()
            .any(|order| order.idempotency_key() == request.idempotency_key())
        {
            return Ok(BrokerOrderAck::new(
                format!("MOCK-{}", request.idempotency_key()),
                request.environment(),
                BrokerOrderStatus::Duplicate,
            )?);
        }

        let ack = BrokerOrderAck::new(
            format!("MOCK-{}", accepted.len() + 1),
            request.environment(),
            BrokerOrderStatus::Accepted,
        )?;
        accepted.push(request);
        Ok(ack)
    }
}

/// Broker validation error.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum BrokerValidationError {
    /// Idempotency key is empty or too long.
    #[error("idempotency key must be 1..=128 ASCII characters after trimming")]
    InvalidIdempotencyKey,
    /// Symbol is empty, too long, or not ASCII.
    #[error("broker symbol must be 1..=32 ASCII characters after trimming")]
    InvalidSymbol,
    /// Decimal field is not positive.
    #[error("{field} must be greater than zero")]
    NonPositiveDecimal {
        /// Field name.
        field: &'static str,
    },
    /// Limit orders require a positive limit price.
    #[error("limit order requires a limit price")]
    MissingLimitPrice,
    /// Market orders must not include a limit price.
    #[error("market order must not include a limit price")]
    UnexpectedLimitPrice,
}

/// Broker adapter error.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum BrokerError {
    /// Request failed validation.
    #[error(transparent)]
    Validation(#[from] BrokerValidationError),
    /// Live trading is disabled by configuration.
    #[error("live trading is disabled")]
    LiveTradingDisabled,
    /// Broker adapter or gateway is unavailable.
    #[error("broker is unavailable")]
    Unavailable,
}

fn normalize_idempotency_key(value: String) -> Result<String, BrokerValidationError> {
    let normalized = value.trim().to_owned();
    if normalized.is_empty() || normalized.len() > MAX_IDEMPOTENCY_KEY_LEN || !normalized.is_ascii()
    {
        Err(BrokerValidationError::InvalidIdempotencyKey)
    } else {
        Ok(normalized)
    }
}

fn normalize_symbol(value: String) -> Result<String, BrokerValidationError> {
    let normalized = value.trim().to_owned();
    if normalized.is_empty() || normalized.len() > MAX_SYMBOL_LEN || !normalized.is_ascii() {
        Err(BrokerValidationError::InvalidSymbol)
    } else {
        Ok(normalized.to_ascii_uppercase())
    }
}

fn validate_positive(field: &'static str, value: Decimal) -> Result<(), BrokerValidationError> {
    if value > Decimal::ZERO {
        Ok(())
    } else {
        Err(BrokerValidationError::NonPositiveDecimal { field })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Parse decimal fixtures without floating-point literals.
    fn money(value: &str) -> Decimal {
        value.parse().unwrap()
    }

    /// Build a valid paper-market order fixture.
    fn paper_market_order(key: &str) -> BrokerOrderRequest {
        BrokerOrderRequest::market(
            key,
            " voo ",
            BrokerOrderSide::Buy,
            money("1.25"),
            BrokerEnvironment::Paper,
        )
        .unwrap()
    }

    /// Verify order constructors normalize text and keep decimal precision.
    #[test]
    fn market_order_normalizes_symbol_and_idempotency_key() {
        let request = paper_market_order(" demo-1 ");

        assert_eq!(request.idempotency_key(), "demo-1");
        assert_eq!(request.symbol(), "VOO");
        assert_eq!(request.side(), BrokerOrderSide::Buy);
        assert_eq!(request.order_type(), BrokerOrderType::Market);
        assert_eq!(request.quantity(), money("1.25"));
        assert_eq!(request.limit_price(), None);
        assert_eq!(request.environment(), BrokerEnvironment::Paper);
    }

    /// Verify limit orders require an explicit positive limit price.
    #[test]
    fn limit_order_requires_positive_limit_price() {
        let request = BrokerOrderRequest::limit(
            "demo-2",
            "VOO",
            BrokerOrderSide::Buy,
            money("1.00"),
            money("400.12"),
            BrokerEnvironment::Paper,
        )
        .unwrap();

        assert_eq!(request.order_type(), BrokerOrderType::Limit);
        assert_eq!(request.limit_price(), Some(money("400.12")));
        assert_eq!(
            BrokerOrderRequest::limit(
                "demo-2",
                "VOO",
                BrokerOrderSide::Buy,
                money("1.00"),
                Decimal::ZERO,
                BrokerEnvironment::Paper,
            ),
            Err(BrokerValidationError::NonPositiveDecimal {
                field: "limit_price"
            })
        );
    }

    /// Verify invalid orders are rejected before any adapter is called.
    #[test]
    fn order_request_rejects_invalid_fields() {
        assert_eq!(
            BrokerOrderRequest::market(
                "",
                "VOO",
                BrokerOrderSide::Buy,
                money("1.00"),
                BrokerEnvironment::Paper,
            ),
            Err(BrokerValidationError::InvalidIdempotencyKey)
        );
        assert_eq!(
            BrokerOrderRequest::market(
                "demo-3",
                "åapl",
                BrokerOrderSide::Buy,
                money("1.00"),
                BrokerEnvironment::Paper,
            ),
            Err(BrokerValidationError::InvalidSymbol)
        );
        assert_eq!(
            BrokerOrderRequest::market(
                "demo-3",
                "AAPL",
                BrokerOrderSide::Buy,
                Decimal::ZERO,
                BrokerEnvironment::Paper,
            ),
            Err(BrokerValidationError::NonPositiveDecimal { field: "quantity" })
        );
    }

    /// Verify mock broker accepts paper orders and records them for demo assertions.
    #[tokio::test]
    async fn mock_broker_accepts_paper_orders() {
        let broker = MockBroker::paper_only();
        let ack = broker
            .submit_order(paper_market_order("demo-4"))
            .await
            .unwrap();

        assert_eq!(ack.order_id(), "MOCK-1");
        assert_eq!(ack.status(), BrokerOrderStatus::Accepted);
        assert_eq!(ack.environment(), BrokerEnvironment::Paper);
        assert_eq!(broker.accepted_orders().len(), 1);
    }

    /// Verify mock broker deduplicates idempotency keys.
    #[tokio::test]
    async fn mock_broker_deduplicates_repeated_idempotency_key() {
        let broker = MockBroker::paper_only();
        broker
            .submit_order(paper_market_order("demo-5"))
            .await
            .unwrap();
        let duplicate = broker
            .submit_order(paper_market_order("demo-5"))
            .await
            .unwrap();

        assert_eq!(duplicate.status(), BrokerOrderStatus::Duplicate);
        assert_eq!(broker.accepted_orders().len(), 1);
    }

    /// Verify live orders are rejected unless explicitly enabled.
    #[tokio::test]
    async fn mock_broker_rejects_live_orders_by_default() {
        let request = BrokerOrderRequest::market(
            "demo-6",
            "VOO",
            BrokerOrderSide::Buy,
            money("1.00"),
            BrokerEnvironment::Live,
        )
        .unwrap();

        assert_eq!(
            MockBroker::paper_only().submit_order(request).await,
            Err(BrokerError::LiveTradingDisabled)
        );
    }
}
