#![forbid(unsafe_code)]
#![deny(missing_docs)]

//! Decision record domain and application port.
//!
//! This crate stores audit-ready decision snapshots. It deliberately keeps
//! external provider details as JSON snapshots so Qwen, quant, and broker
//! adapters can evolve without losing the exact input and output seen at
//! decision time.

use std::sync::Arc;

use async_trait::async_trait;
use rust_decimal::Decimal;
use serde::Serialize;
use serde_json::Value;
use time::OffsetDateTime;
use uuid::Uuid;

const MAX_SYMBOL_LEN: usize = 32;
const MAX_SUMMARY_LEN: usize = 2000;

/// Execution status captured by a decision record.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum DecisionExecutionStatus {
    /// The plan is active and the preview date matches the schedule.
    Due,
    /// The plan is active but the preview date is not the schedule date.
    Waiting,
    /// The plan is inactive and should not execute.
    Inactive,
}

/// Persisted decision record for one preview or execution.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct DecisionRecord {
    /// Record ID.
    pub id: Uuid,
    /// Related investment plan ID.
    pub plan_id: Uuid,
    /// Investment symbol snapshot.
    pub symbol: String,
    /// Currency snapshot.
    pub currency: String,
    /// Execution status snapshot.
    pub execution_status: DecisionExecutionStatus,
    /// Optional planned contribution encoded as a decimal string.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub planned_contribution: Option<String>,
    /// Execution preview snapshot, including schedule and bucket split.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    pub execution_snapshot: Value,
    /// Fundamental input snapshot used by the decision engine.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    pub fundamental_snapshot: Value,
    /// Trend input snapshot used by the decision engine.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    pub trend_snapshot: Value,
    /// Optional AI sentiment snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sentiment_snapshot: Option<Value>,
    /// Decision output snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    pub decision_snapshot: Value,
    /// Optional broker order request snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub broker_order_request: Option<Value>,
    /// Optional broker order acknowledgement snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub broker_order_ack: Option<Value>,
    /// User-facing summary generated for this decision.
    pub summary: String,
    /// Creation time.
    pub created_at: OffsetDateTime,
}

/// Input used to create a decision record.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct CreateDecisionRecord {
    /// Related investment plan ID.
    pub plan_id: Uuid,
    /// Investment symbol snapshot.
    pub symbol: String,
    /// Currency snapshot.
    pub currency: String,
    /// Execution status snapshot.
    pub execution_status: DecisionExecutionStatus,
    /// Optional planned contribution encoded as a decimal string.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub planned_contribution: Option<String>,
    /// Execution preview snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    pub execution_snapshot: Value,
    /// Fundamental input snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    pub fundamental_snapshot: Value,
    /// Trend input snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    pub trend_snapshot: Value,
    /// Optional AI sentiment snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sentiment_snapshot: Option<Value>,
    /// Decision output snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    pub decision_snapshot: Value,
    /// Optional broker order request snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub broker_order_request: Option<Value>,
    /// Optional broker order acknowledgement snapshot.
    ///
    /// Snapshots must be generated by trusted backend orchestration and must
    /// not contain API keys, account IDs, OpenD passwords, or other secrets.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub broker_order_ack: Option<Value>,
    /// User-facing summary generated for this decision.
    pub summary: String,
}

impl CreateDecisionRecord {
    /// Normalize and validate an inbound decision record before persistence.
    pub fn normalize(self) -> Result<Self, DecisionRecordValidationError> {
        let symbol = normalize_symbol(self.symbol)?;
        let currency = normalize_currency(self.currency)?;
        let planned_contribution = self
            .planned_contribution
            .map(normalize_decimal_string)
            .transpose()?;
        validate_snapshot(&self.execution_snapshot, "execution_snapshot")?;
        validate_snapshot(&self.fundamental_snapshot, "fundamental_snapshot")?;
        validate_snapshot(&self.trend_snapshot, "trend_snapshot")?;
        if let Some(snapshot) = &self.sentiment_snapshot {
            validate_snapshot(snapshot, "sentiment_snapshot")?;
        }
        validate_snapshot(&self.decision_snapshot, "decision_snapshot")?;
        if let Some(snapshot) = &self.broker_order_request {
            validate_snapshot(snapshot, "broker_order_request")?;
        }
        if let Some(snapshot) = &self.broker_order_ack {
            validate_snapshot(snapshot, "broker_order_ack")?;
        }
        let summary = normalize_summary(self.summary)?;

        Ok(Self {
            symbol,
            currency,
            planned_contribution,
            summary,
            ..self
        })
    }
}

/// Decision record validation error.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum DecisionRecordValidationError {
    /// Symbol is empty, too long, non-ASCII, or contains control characters.
    #[error("decision record symbol is invalid")]
    InvalidSymbol,
    /// Currency is not a three-letter uppercase ASCII code.
    #[error("decision record currency is invalid")]
    InvalidCurrency,
    /// Decimal string is empty, malformed, or non-positive.
    #[error("decision record decimal string is invalid")]
    InvalidDecimalString,
    /// Required JSON snapshot is null.
    #[error("decision record snapshot is invalid: {field}")]
    InvalidSnapshot {
        /// Snapshot field name.
        field: &'static str,
    },
    /// Summary is empty or too long.
    #[error("decision record summary is invalid")]
    InvalidSummary,
}

/// Repository errors hidden behind the application layer.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum DecisionRecordRepositoryError {
    /// The decision record did not pass domain validation.
    #[error(transparent)]
    Validation(#[from] DecisionRecordValidationError),
    /// The requested decision record does not exist.
    #[error("decision record not found")]
    NotFound,
    /// The storage backend is unavailable.
    #[error("decision record repository unavailable")]
    Unavailable,
}

/// Application-layer errors for decision records.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum DecisionRecordApplicationError {
    /// The decision record did not pass domain validation.
    #[error(transparent)]
    Validation(#[from] DecisionRecordValidationError),
    /// The requested decision record does not exist.
    #[error("decision record not found")]
    NotFound,
    /// The decision record backend is unavailable.
    #[error("decision record backend unavailable")]
    Unavailable,
}

impl From<DecisionRecordRepositoryError> for DecisionRecordApplicationError {
    fn from(error: DecisionRecordRepositoryError) -> Self {
        match error {
            DecisionRecordRepositoryError::Validation(error) => Self::Validation(error),
            DecisionRecordRepositoryError::NotFound => Self::NotFound,
            DecisionRecordRepositoryError::Unavailable => Self::Unavailable,
        }
    }
}

/// Outbound repository port for decision records.
#[async_trait]
pub trait DecisionRecordRepository: Send + Sync {
    /// Persist one decision record snapshot.
    async fn create(
        &self,
        input: CreateDecisionRecord,
    ) -> Result<DecisionRecord, DecisionRecordRepositoryError>;

    /// List decision records for one investment plan.
    async fn list_by_plan(
        &self,
        plan_id: Uuid,
    ) -> Result<Vec<DecisionRecord>, DecisionRecordRepositoryError>;

    /// Fetch one decision record by ID.
    async fn get(&self, id: Uuid) -> Result<DecisionRecord, DecisionRecordRepositoryError>;
}

/// Application service for decision record use cases.
#[derive(Clone)]
pub struct DecisionRecordService {
    repository: Arc<dyn DecisionRecordRepository>,
}

impl DecisionRecordService {
    /// Build the service from a repository implementation.
    #[must_use]
    pub fn new(repository: Arc<dyn DecisionRecordRepository>) -> Self {
        Self { repository }
    }

    /// Persist one decision record snapshot.
    ///
    /// # Errors
    ///
    /// Returns [`DecisionRecordApplicationError::Unavailable`] if storage is unavailable.
    pub async fn create(
        &self,
        input: CreateDecisionRecord,
    ) -> Result<DecisionRecord, DecisionRecordApplicationError> {
        self.repository
            .create(input.normalize()?)
            .await
            .map_err(Into::into)
    }

    /// List decision records for one investment plan.
    ///
    /// # Errors
    ///
    /// Returns [`DecisionRecordApplicationError::Unavailable`] if storage is unavailable.
    pub async fn list_by_plan(
        &self,
        plan_id: Uuid,
    ) -> Result<Vec<DecisionRecord>, DecisionRecordApplicationError> {
        self.repository
            .list_by_plan(plan_id)
            .await
            .map_err(Into::into)
    }

    /// Fetch one decision record by ID.
    ///
    /// # Errors
    ///
    /// Returns [`DecisionRecordApplicationError::NotFound`] when the record does not exist,
    /// or [`DecisionRecordApplicationError::Unavailable`] if storage is unavailable.
    pub async fn get(&self, id: Uuid) -> Result<DecisionRecord, DecisionRecordApplicationError> {
        self.repository.get(id).await.map_err(Into::into)
    }
}

fn normalize_symbol(value: String) -> Result<String, DecisionRecordValidationError> {
    let normalized = value.trim().to_owned();
    if normalized.is_empty()
        || normalized.len() > MAX_SYMBOL_LEN
        || !normalized.is_ascii()
        || normalized.chars().any(char::is_control)
    {
        return Err(DecisionRecordValidationError::InvalidSymbol);
    }

    Ok(normalized.to_ascii_uppercase())
}

fn normalize_currency(value: String) -> Result<String, DecisionRecordValidationError> {
    let normalized = value.trim().to_ascii_uppercase();
    if normalized.len() == 3
        && normalized
            .chars()
            .all(|character| character.is_ascii_uppercase())
    {
        Ok(normalized)
    } else {
        Err(DecisionRecordValidationError::InvalidCurrency)
    }
}

fn normalize_decimal_string(value: String) -> Result<String, DecisionRecordValidationError> {
    let normalized = value.trim();
    if normalized.is_empty()
        || normalized
            .parse::<Decimal>()
            .map_or(true, |value| value <= Decimal::ZERO)
    {
        Err(DecisionRecordValidationError::InvalidDecimalString)
    } else {
        Ok(normalized.to_owned())
    }
}

fn validate_snapshot(
    value: &Value,
    field: &'static str,
) -> Result<(), DecisionRecordValidationError> {
    if value.is_null() {
        Err(DecisionRecordValidationError::InvalidSnapshot { field })
    } else {
        Ok(())
    }
}

fn normalize_summary(value: String) -> Result<String, DecisionRecordValidationError> {
    let normalized = value.trim().to_owned();
    if normalized.is_empty() || normalized.len() > MAX_SUMMARY_LEN {
        Err(DecisionRecordValidationError::InvalidSummary)
    } else {
        Ok(normalized)
    }
}

#[cfg(test)]
mod tests {
    use std::sync::Mutex;

    use serde_json::json;

    use super::*;

    #[derive(Default)]
    struct FakeRepository {
        records: Mutex<Vec<DecisionRecord>>,
    }

    #[async_trait]
    impl DecisionRecordRepository for FakeRepository {
        async fn create(
            &self,
            input: CreateDecisionRecord,
        ) -> Result<DecisionRecord, DecisionRecordRepositoryError> {
            let mut records = self.records.lock().unwrap();
            let record = record_from(Uuid::from_u128((records.len() + 1) as u128), input);
            records.push(record.clone());
            Ok(record)
        }

        async fn list_by_plan(
            &self,
            plan_id: Uuid,
        ) -> Result<Vec<DecisionRecord>, DecisionRecordRepositoryError> {
            Ok(self
                .records
                .lock()
                .unwrap()
                .iter()
                .filter(|record| record.plan_id == plan_id)
                .cloned()
                .collect())
        }

        async fn get(&self, id: Uuid) -> Result<DecisionRecord, DecisionRecordRepositoryError> {
            self.records
                .lock()
                .unwrap()
                .iter()
                .find(|record| record.id == id)
                .cloned()
                .ok_or(DecisionRecordRepositoryError::NotFound)
        }
    }

    fn input(plan_id: Uuid) -> CreateDecisionRecord {
        CreateDecisionRecord {
            plan_id,
            symbol: "VOO".to_owned(),
            currency: "USD".to_owned(),
            execution_status: DecisionExecutionStatus::Due,
            planned_contribution: Some("1000.00".to_owned()),
            execution_snapshot: json!({"status": "due"}),
            fundamental_snapshot: json!({"score": 0.2}),
            trend_snapshot: json!({"score": 0.5}),
            sentiment_snapshot: Some(json!({"score": 0.1})),
            decision_snapshot: json!({"action": "standard"}),
            broker_order_request: Some(json!({"side": "buy"})),
            broker_order_ack: Some(json!({"status": "accepted"})),
            summary: "standard execution".to_owned(),
        }
    }

    fn record_from(id: Uuid, input: CreateDecisionRecord) -> DecisionRecord {
        DecisionRecord {
            id,
            plan_id: input.plan_id,
            symbol: input.symbol,
            currency: input.currency,
            execution_status: input.execution_status,
            planned_contribution: input.planned_contribution,
            execution_snapshot: input.execution_snapshot,
            fundamental_snapshot: input.fundamental_snapshot,
            trend_snapshot: input.trend_snapshot,
            sentiment_snapshot: input.sentiment_snapshot,
            decision_snapshot: input.decision_snapshot,
            broker_order_request: input.broker_order_request,
            broker_order_ack: input.broker_order_ack,
            summary: input.summary,
            created_at: OffsetDateTime::from_unix_timestamp(1_700_000_000).unwrap(),
        }
    }

    #[tokio::test]
    async fn service_creates_lists_and_gets_records() {
        let repository = Arc::new(FakeRepository::default());
        let service = DecisionRecordService::new(repository);
        let plan_id = Uuid::from_u128(7);
        let created = service.create(input(plan_id)).await.unwrap();

        assert_eq!(created.plan_id, plan_id);
        assert_eq!(created.execution_snapshot, json!({"status": "due"}));
        assert_eq!(
            service.list_by_plan(plan_id).await.unwrap(),
            vec![created.clone()]
        );
        assert_eq!(service.get(created.id).await.unwrap(), created);
    }

    #[tokio::test]
    async fn service_maps_repository_not_found() {
        let service = DecisionRecordService::new(Arc::new(FakeRepository::default()));

        assert_eq!(
            service.get(Uuid::from_u128(404)).await,
            Err(DecisionRecordApplicationError::NotFound)
        );
    }

    #[tokio::test]
    async fn service_normalizes_create_input_before_repository() {
        let repository = Arc::new(FakeRepository::default());
        let service = DecisionRecordService::new(repository);
        let mut input = input(Uuid::from_u128(7));
        input.symbol = " voo ".to_owned();
        input.currency = " usd ".to_owned();
        input.planned_contribution = Some(" 1000.00 ".to_owned());
        input.summary = " standard execution ".to_owned();

        let created = service.create(input).await.unwrap();

        assert_eq!(created.symbol, "VOO");
        assert_eq!(created.currency, "USD");
        assert_eq!(created.planned_contribution, Some("1000.00".to_owned()));
        assert_eq!(created.summary, "standard execution");
    }

    #[tokio::test]
    async fn service_rejects_invalid_create_input_before_repository() {
        let service = DecisionRecordService::new(Arc::new(FakeRepository::default()));
        let mut invalid_decimal = input(Uuid::from_u128(7));
        invalid_decimal.planned_contribution = Some("NaN".to_owned());

        assert_eq!(
            service.create(invalid_decimal).await,
            Err(DecisionRecordApplicationError::Validation(
                DecisionRecordValidationError::InvalidDecimalString
            ))
        );

        let mut invalid_snapshot = input(Uuid::from_u128(7));
        invalid_snapshot.execution_snapshot = Value::Null;

        assert_eq!(
            service.create(invalid_snapshot).await,
            Err(DecisionRecordApplicationError::Validation(
                DecisionRecordValidationError::InvalidSnapshot {
                    field: "execution_snapshot"
                }
            ))
        );
    }
}
